# Generated by Django 3.2.12 on 2022-02-21 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_auto_20220221_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='collegium',
            field=models.ManyToManyField(related_name='collegium', through='cases.CollegiumMembership', to=settings.AUTH_USER_MODEL, verbose_name='Члени колегії'),
        ),
    ]
