# Generated by Django 3.2.12 on 2022-03-10 12:53

import apps.cases.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_case_collegium'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to=apps.cases.utils.document_get_original_file_path, verbose_name='Оригінальний файл документа'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('file', models.FileField(upload_to=apps.cases.utils.sign_get_file_path)),
                ('subject', models.CharField(max_length=255, verbose_name='Підписант')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серійний номер')),
                ('issuer', models.CharField(max_length=255, verbose_name='Надавач послуг (АЦСК)')),
                ('timestamp', models.CharField(max_length=255, verbose_name='Мітка часу')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.document', verbose_name='Документ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Цифровий підпис',
                'verbose_name_plural': 'Цифрові підписи',
                'db_table': 'cases_documents_signs',
            },
        ),
    ]
