# Generated by Django 3.2.12 on 2022-05-20 09:17

import apps.cases.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_auto_20220310_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegiummembership',
            options={'verbose_name': 'Колегія', 'verbose_name_plural': 'Колегія'},
        ),
        migrations.AlterField(
            model_name='collegiummembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Особа'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='file',
            field=models.FileField(upload_to=apps.cases.utils.sign_get_file_path, verbose_name='Файл з цифровим підписом (.p7s)'),
        ),
    ]
