# Generated by Django 3.2.12 on 2022-06-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20220607_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенеровано автоматично'),
        ),
    ]
