# Generated by Django 3.2.12 on 2022-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_document_claim_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='appellant_reqs',
            field=models.BooleanField(default=False, verbose_name='Вимоги апелянта'),
        ),
    ]
