# Generated by Django 3.2.12 on 2022-06-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_document_appellant_reqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
    ]
