# Generated by Django 3.2.12 on 2022-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0007_documenttype_claim_kinds'),
        ('cases', '0011_remove_document_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва шаблону')),
                ('file', models.FileField(upload_to='doc-templates/', verbose_name='Файл')),
                ('documents_types', models.ManyToManyField(to='classifiers.DocumentType', verbose_name='Типи документів')),
            ],
            options={
                'verbose_name': 'Цифровий підпис',
                'verbose_name_plural': 'Цифрові підписи',
                'db_table': 'documents_templates',
            },
        ),
    ]
