# Generated by Django 3.2.12 on 2022-06-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0013_remove_claimfield_base_doc'),
        ('cases', '0015_alter_documenttemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filling.claim', verbose_name='Звернення'),
        ),
    ]
