# Generated by Django 3.2.12 on 2022-06-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_case_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='app_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='applicant_represent',
        ),
        migrations.RemoveField(
            model_name='case',
            name='claim_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='claim_kind',
        ),
        migrations.RemoveField(
            model_name='case',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='case',
            name='obj_kind',
        ),
        migrations.RemoveField(
            model_name='case',
            name='obj_title',
        ),
        migrations.AlterField(
            model_name='case',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата, до якої необхідно розглянути звернення'),
        ),
    ]
