# Generated by Django 3.2.12 on 2022-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20220627_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='file_signed',
            field=models.FileField(default='', upload_to='', verbose_name='Підписаний файл'),
            preserve_default=False,
        ),
    ]
