# Generated by Django 4.0.6 on 2022-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_case_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Нове звернення'), (1, 'Створення розпорядження про створення колегії'), (2, 'Прийняття до розгляду звернення'), (3, 'Розгляд звернення'), (8, 'Розгляд звернення')], default=0, verbose_name='Стадія розгляду'),
        ),
    ]
