# Generated by Django 4.0.6 on 2022-07-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_case_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва стадії')),
            ],
            options={
                'verbose_name': 'Стадія справи',
                'verbose_name_plural': 'Стадії справи',
                'db_table': 'cases_stage',
            },
        ),
        migrations.RemoveField(
            model_name='case',
            name='stage',
        ),
        migrations.CreateModel(
            name='CaseStageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=1024, verbose_name='Назва етапу')),
                ('code', models.CharField(max_length=16, verbose_name='Код етапу')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.casestage', verbose_name='Стадія')),
            ],
            options={
                'verbose_name': 'Етап стадії справи',
                'verbose_name_plural': 'Етапи стадій справ',
                'db_table': 'cases_stage_item',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='stage_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casestageitem', verbose_name='Етап стадії розгляду'),
        ),
    ]
