# Generated by Django 4.0.6 on 2022-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_casestage_remove_case_stage_casestageitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestage',
            name='number',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Номер стадії'),
        ),
    ]
