# Generated by Django 4.0.6 on 2022-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_casestage_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStageItem',
            new_name='CaseStageStep',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='stage_item',
            new_name='stage_step',
        ),
    ]
