# Generated by Django 4.0.6 on 2022-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_rename_casestageitem_casestagestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
