# Generated by Django 4.0.6 on 2022-07-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_document_barcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casestagestep',
            table='cases_stage_step',
        ),
    ]
