# Generated by Django 4.0.6 on 2022-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_casestagestep_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='input_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отримання'),
        ),
        migrations.AlterField(
            model_name='document',
            name='output_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата відправлення'),
        ),
        migrations.AlterField(
            model_name='document',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата реєстрації'),
        ),
    ]
