# Generated by Django 4.0.6 on 2022-08-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_alter_document_input_date_alter_document_output_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestagestep',
            name='case_stopped',
            field=models.BooleanField(default=False, verbose_name='Діловодство припинено'),
        ),
    ]
