# Generated by Django 4.0.6 on 2022-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_casehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestagestep',
            name='code',
            field=models.PositiveIntegerField(verbose_name='Код етапу'),
        ),
    ]
