# Generated by Django 4.0.6 on 2022-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0013_refusalreason'),
        ('cases', '0030_alter_casestagestep_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='refusal_reasons',
            field=models.ManyToManyField(blank=True, to='classifiers.refusalreason', verbose_name='Підстави для відмови у наданні правової охорони'),
        ),
    ]
