# Generated by Django 4.0.6 on 2022-09-28 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0032_delete_documenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('action', models.CharField(max_length=1024, verbose_name='Дія')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.document', verbose_name='Документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Дія по документу',
                'verbose_name_plural': 'Дії по документу',
                'db_table': 'documents_history',
            },
        ),
    ]
