# Generated by Django 4.0.6 on 2022-10-14 20:14

import apps.cases.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_rename_case_documenthistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='paused',
            field=models.BooleanField(default=False, verbose_name='Діловодство по справі зупинене'),
        ),
        migrations.AddField(
            model_name='case',
            name='stopped',
            field=models.BooleanField(default=False, verbose_name='Розгляд справи припинений'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.cases.utils.document_get_original_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Оригінальний файл документа'),
        ),
    ]
