# Generated by Django 4.0.6 on 2022-10-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_case_paused_case_stopped_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestagestep',
            name='case_stopped',
        ),
    ]
