# Generated by Django 4.0.6 on 2022-10-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_remove_casestagestep_case_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Видалено'),
        ),
    ]
