# Generated by Django 4.0.6 on 2022-11-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_document_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='converted_to_pdf',
            field=models.BooleanField(default=False, verbose_name='Конвертовано у pdf'),
        ),
    ]
