# Generated by Django 4.0.6 on 2022-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_document_converted_to_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='case',
            name='addressee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресат'),
        ),
    ]
