# Generated by Django 4.0.6 on 2022-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_case_address_case_addressee'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='can_be_edited',
            field=models.BooleanField(default=True, verbose_name='Може бути відредагований до підписання'),
        ),
    ]
