# Generated by Django 4.0.6 on 2022-11-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0021_decisiontype'),
        ('cases', '0040_document_can_be_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='decision_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifiers.decisiontype', verbose_name='Рішення Апеляційної палати'),
        ),
    ]
