# Generated by Django 4.0.6 on 2022-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_case_decision_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalProtocolExchange',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('id_cead', models.IntegerField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('send_to_chancellary', models.DateTimeField(blank=True, null=True)),
                ('send_to_recipient', models.DateTimeField(blank=True, null=True)),
                ('date_of_receiving', models.DateTimeField(blank=True, null=True)),
                ('date_of_postal_return', models.DateTimeField(blank=True, null=True)),
                ('postal_return_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancel_sending_document_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_sending_document_reason', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'postal_protocol_exchange',
                'managed': False,
            },
        ),
    ]
