# Generated by Django 4.0.6 on 2022-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0042_postalprotocolexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(db_column='id_command', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(blank=True, null=True)),
                ('is_error', models.BooleanField(blank=True, null=True)),
                ('error_datetime', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'ls_list_commands',
                'managed': False,
            },
        ),
    ]
