# Generated by Django 4.0.6 on 2022-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оголошення рішення АП'),
        ),
    ]
