# Generated by Django 4.0.6 on 2022-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0044_case_decision_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsignProtocolExchange',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('id_cead', models.IntegerField(blank=True, null=True)),
                ('date_saved_at', models.DateTimeField(blank=True, null=True)),
                ('date_export_to_esignserice', models.DateTimeField(blank=True, null=True)),
                ('date_import_from_esignservice', models.DateTimeField(blank=True, null=True)),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('esign_body', models.BinaryField(blank=True, max_length='max', null=True)),
                ('signer_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'esign_protocol_exchange',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='sign',
            name='external_service_sign',
            field=models.BooleanField(default=False, verbose_name='Файл підписано зовнішнім сервісом'),
        ),
    ]
