# Generated by Django 4.0.6 on 2022-12-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_esignprotocolexchange_sign_external_service_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='hearing',
        ),
        migrations.AddField(
            model_name='case',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата та час публікації на веб-сайті'),
        ),
    ]
