# Generated by Django 4.0.6 on 2022-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0047_case_stop_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата припинення розгляду справи'),
        ),
    ]
