[tool.poetry]
name = "appeals"
version = "0.1.0"
description = ""
authors = ["Alexandr Monastyrtesky <alex.mon1989@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "3.2.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
