# Generated by Django 3.2.12 on 2022-05-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0004_claimkind_third_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=512, verbose_name='Назва')),
                ('input_id', models.CharField(max_length=32, verbose_name='ID поля вводу')),
                ('field_type', models.CharField(choices=[('text', 'Текстове поле'), ('textarea', 'Текстова область'), ('date', 'Поле вибору дати'), ('file', 'Поле вибору файла')], default='text', max_length=8, verbose_name='Тип поля')),
                ('stage', models.PositiveIntegerField(choices=[(4, 4), (5, 5), (6, 6), (7, 7)], verbose_name='Етап вводу на формі')),
                ('editable', models.BooleanField(default=True, verbose_name='Можливо редагувати')),
                ('claim_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifiers.claimkind', verbose_name='Тип звернення')),
            ],
            options={
                'verbose_name': 'Поле звернення',
                'verbose_name_plural': 'Поля звернень',
            },
        ),
    ]
