# Generated by Django 3.2.12 on 2022-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfield',
            name='help_text',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Допоміжний текст'),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текстове поле'), ('textarea', 'Текстова область'), ('date', 'Поле вибору дати'), ('file', 'Поле вибору файла'), ('file_multi', 'Поле вибору файла')], default='text', max_length=10, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='stage',
            field=models.PositiveIntegerField(choices=[(3, 'Номер заявки, номер охоронного документа'), (4, 'Відомості про заявника (апелянта) та власника'), (5, 'Відомостей  про апелянта  лише у випадку заперечень 3-х осіб і апеляційних заяв'), (6, 'Відомості для заперечень (поля дат)'), (7, 'Відомості для заперечень (файли)'), (8, 'Додатки до заперечення, апеляційної заяви, заяви про визнання ТМ ДВ')], verbose_name='Етап вводу на формі'),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
