# Generated by Django 3.2.12 on 2022-06-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0005_objkind_sis_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filling', '0006_claimfield_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('obj_number', models.CharField(max_length=255, verbose_name='Номер заявки або охоронного документа')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Потребує підписання документів'), (2, 'Очікує на розгляд'), (3, 'Створено справу')], default=1, verbose_name='Статус')),
                ('json_data', models.TextField(blank=True, null=True, verbose_name='Дані звернення')),
                ('claim_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.claimkind', verbose_name='Вид звернення')),
                ('obj_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifiers.objkind', verbose_name="Тип об'єкта")),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
            },
        ),
    ]
