# Generated by Django 3.2.12 on 2022-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0008_claim_third_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Потребує підписання документів'), (2, 'Очікує передачі на розгляд'), (3, 'Передано на розгляд'), (4, 'Створено справу')], default=1, verbose_name='Статус'),
        ),
    ]
