# Generated by Django 3.2.12 on 2022-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0009_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Потребує підписання документів'), (2, 'Готове до подання'), (3, 'Створено справу')], default=1, verbose_name='Статус'),
        ),
    ]
