# Generated by Django 3.2.12 on 2022-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0010_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfield',
            name='base_doc',
            field=models.BooleanField(default=False, verbose_name='Базовий документ для формування документу звернення'),
        ),
    ]
