# Generated by Django 3.2.12 on 2022-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0011_claimfield_base_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimfield',
            name='allowed_extensions',
            field=models.CharField(blank=True, help_text='Перелічте дозволені формати через кому (напр, ".doc, .docx"). Має ефект тільки якщо тип поля - "Поле вибору файла".', max_length=255, null=True, verbose_name='Дозволені формати файлу'),
        ),
        migrations.AlterField(
            model_name='claimfield',
            name='base_doc',
            field=models.BooleanField(default=False, help_text='Має ефект тільки якщо тип поля - "Поле вибору файла".', verbose_name='Базовий документ для формування документу звернення'),
        ),
    ]
