# Generated by Django 3.2.12 on 2022-06-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0012_auto_20220620_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimfield',
            name='base_doc',
        ),
    ]
