# Generated by Django 4.0.6 on 2022-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0014_claim_obj_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Створено'),
        ),
    ]
