# Generated by Django 4.0.6 on 2022-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0015_claim_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Створено'),
        ),
    ]
