# Generated by Django 4.0.6 on 2022-12-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling', '0017_claim_internal_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appellant',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='filling.claim', verbose_name='Звернення')),
                ('title', models.CharField(max_length=512, verbose_name='Найменування апелянта')),
                ('address', models.CharField(max_length=512, verbose_name='Адреса апелянта')),
                ('email', models.CharField(max_length=32, verbose_name='E-Mail апелянта')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон апелянта')),
                ('person_type', models.CharField(blank=True, choices=[('individual', 'Фізична особа'), ('entity', 'Юридична особа')], max_length=16, null=True, verbose_name='Тип особи')),
                ('is_representative', models.BooleanField(default=False, verbose_name='Є представником')),
                ('representative_type', models.CharField(blank=True, choices=[('patent_attorney', 'Патентний повірений'), ('lawyer', 'Адвокат'), ('other', 'Інше')], max_length=16, null=True, verbose_name='Тип поля')),
                ('resident', models.BooleanField(default=True, verbose_name='Резидент / не резидент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Апелянт',
                'verbose_name_plural': 'Апелянти',
                'db_table': 'filling_appellants',
            },
        ),
        migrations.AlterField(
            model_name='claim',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата та час подачі'),
        ),
    ]
