# Generated by Django 4.0.6 on 2022-12-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0027_claimpersontype'),
        ('filling', '0018_appellant_alter_claim_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.TextField(max_length=1024, verbose_name='Найменування особи')),
                ('address', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Адреса особи')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filling.claim', verbose_name='Звернення')),
                ('person_type', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='classifiers.claimpersontype', verbose_name='Тип особи')),
            ],
            options={
                'verbose_name': 'Особа звернення',
                'verbose_name_plural': 'Особи звернення',
                'db_table': 'filling_claim_persons',
            },
        ),
    ]
