# Generated by Django 4.0.6 on 2022-09-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('message', models.CharField(max_length=255, verbose_name='Текст повідомлення')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='Рівень повідомлення')),
                ('read', models.BooleanField(verbose_name='Прочитано адресатом', default=False)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Особа, якій адресовано повідомлення')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'db_table': 'notifications_notifications_list',
            },
        ),
    ]
