# Generated by Django 3.2.12 on 2022-05-31 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220221_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('pszIssuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ім’я ЦСК, що видав сертифікат')),
                ('pszIssuerCN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквізити ЦСК, що видав сертифікат')),
                ('pszSerial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реєстраційний номер сертифіката')),
                ('pszSubject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ім’я власника сертифіката')),
                ('pszSubjCN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквізити власника сертифіката')),
                ('pszSubjOrg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Організація до якої належить власник сертифіката')),
                ('pszSubjOrgUnit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Підрозділ організації до якої належить власник сертифіката')),
                ('pszSubjTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Посада власника сертифіката')),
                ('pszSubjState', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва області до якої належить власник сертифіката')),
                ('pszSubjFullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повне ім’я власника сертифіката')),
                ('pszSubjAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса власника сертифіката')),
                ('pszSubjPhone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефону власника сертифіката')),
                ('pszSubjEMail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса електронної пошти власника сертифіката')),
                ('pszSubjDNS', models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS-ім`я чи інше технічного засобу')),
                ('pszSubjEDRPOUCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ЄДРПОУ власника сертифіката')),
                ('pszSubjDRFOCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ДРФО власника сертифіката')),
                ('pszSubjLocality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality власника сертифіката')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
            },
        ),
    ]
