# Generated by Django 4.0.6 on 2022-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0016_speciality_alter_claimkind_obj_state'),
        ('users', '0007_alter_certificateowner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='classifiers.objkind', verbose_name='Спеціальності'),
        ),
    ]
