# Generated by Django 4.0.6 on 2022-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Посада'),
        ),
    ]
