# Generated by Django 4.0.6 on 2022-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Вкажіть повну посаду із відділом, наприклад, "Начальник відділу забезпечення діяльності колегіальних органів Укрпатенту"', max_length=512, null=True, verbose_name='Посада'),
        ),
    ]
