# Generated by Django 4.0.6 on 2022-09-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name_genitive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я у родовому відмінку"),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_genitive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище у родовому відмінку'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name_genitive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По-батькові у родовому відмінку'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_genitive',
            field=models.CharField(blank=True, help_text='Вкажіть повну посаду із відділом, наприклад, "Начальнику відділу забезпечення діяльності колегіальних органів Укрпатенту"', max_length=512, null=True, verbose_name='Посада у родовому відмінку'),
        ),
    ]
