# Generated by Django 3.2.12 on 2022-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Вид заяви/заперечення',
                'verbose_name_plural': 'Види заяв/заперечень',
                'db_table': 'cl_claim_kinds',
            },
        ),
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Назва документа',
                'verbose_name_plural': 'Назви документів',
                'db_table': 'cl_document_names',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типи документів',
                'db_table': 'cl_document_kinds',
            },
        ),
        migrations.CreateModel(
            name='ObjKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': "Вид об'єкта промислової власності",
                'verbose_name_plural': "Види об'єктів промислової власності",
                'db_table': 'cl_obj_kinds',
            },
        ),
    ]
