# Generated by Django 3.2.12 on 2022-05-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_auto_20220221_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimkind',
            name='obj_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifiers.objkind', verbose_name="Вид об'єкта промислової власності"),
        ),
    ]
