# Generated by Django 3.2.12 on 2022-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_claimkind_obj_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimkind',
            name='third_person',
            field=models.BooleanField(default=False, verbose_name='3-тя особа'),
        ),
    ]
