# Generated by Django 3.2.12 on 2022-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_claimkind_third_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='objkind',
            name='sis_id',
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Id типу об'єкта у СІС"),
        ),
    ]
