# Generated by Django 3.2.12 on 2022-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_document_document_name'),
        ('classifiers', '0005_objkind_sis_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentName',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код (ідентифікатор) документа'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='direction',
            field=models.CharField(blank=True, choices=[('internal', 'Внутрішній'), ('external', 'Зовнішній')], max_length=16, null=True, verbose_name='Напрямок'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='origin',
            field=models.CharField(blank=True, choices=[('internal', 'Вхідний'), ('external', 'Вихідний')], max_length=16, null=True, verbose_name='Походження'),
        ),
    ]
