# Generated by Django 3.2.12 on 2022-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0006_auto_20220616_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='claim_kinds',
            field=models.ManyToManyField(to='classifiers.ClaimKind', verbose_name='Види звернень'),
        ),
    ]
