# Generated by Django 3.2.12 on 2022-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0007_documenttype_claim_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='claim_kinds',
            field=models.ManyToManyField(blank=True, to='classifiers.ClaimKind', verbose_name='Види звернень'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Назва'),
        ),
    ]
