# Generated by Django 3.2.12 on 2022-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0008_auto_20220617_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='direction',
            field=models.CharField(blank=True, choices=[('internal', 'Вхідний'), ('external', 'Вихідний')], max_length=16, null=True, verbose_name='Напрямок'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='origin',
            field=models.CharField(blank=True, choices=[('internal', 'Внутрішній'), ('external', 'Зовнішній')], max_length=16, null=True, verbose_name='Походження'),
        ),
    ]
