# Generated by Django 3.2.12 on 2022-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0009_auto_20220617_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='create_with_claim',
            field=models.BooleanField(default=False, verbose_name='Створювати автоматично разом із зверненням'),
        ),
    ]
