# Generated by Django 3.2.12 on 2022-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0011_claimkind_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='base_doc',
            field=models.BooleanField(default=False, verbose_name='Базовий документ для формування документу звернення'),
        ),
    ]
