# Generated by Django 4.0.6 on 2022-08-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0012_documenttype_base_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefusalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('obj_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifiers.objkind', verbose_name="Вид об'єкта промислової власності")),
            ],
            options={
                'verbose_name': 'Підстава для відмови у наданні правової охорони',
                'verbose_name_plural': 'Підстави для відмови у наданні правової охорони',
                'db_table': 'cl_refusal_reasons',
            },
        ),
    ]
