# Generated by Django 4.0.6 on 2022-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0013_refusalreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimkind',
            name='obj_state',
            field=models.PositiveIntegerField(choices=[(1, 'Application'), (2, 'Protective Doc')], default=1, verbose_name="Статус об'єкта"),
        ),
    ]
