# Generated by Django 4.0.6 on 2022-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0014_claimkind_obj_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimkind',
            name='claim_sense',
            field=models.CharField(blank=True, choices=[('DE', 'Заперечення'), ('AP', 'Апеляційна заява')], max_length=2, null=True, verbose_name='Суть типу звернення'),
        ),
    ]
