# Generated by Django 4.0.6 on 2022-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0015_claimkind_claim_sense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Спеціальність члена АП',
                'verbose_name_plural': 'Спеціальністі члені АП',
                'db_table': 'cl_specialities',
            },
        ),
        migrations.AlterField(
            model_name='claimkind',
            name='obj_state',
            field=models.PositiveIntegerField(choices=[(1, 'Заявка'), (2, 'Охоронний документ')], default=1, verbose_name="Статус об'єкта"),
        ),
    ]
