# Generated by Django 4.0.6 on 2022-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0016_speciality_alter_claimkind_obj_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='muc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MUC (технологічний код з GLOC)'),
        ),
    ]
