# Generated by Django 4.0.6 on 2022-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0017_documenttype_muc'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='doc-templates/', verbose_name='Шаблон документу'),
        ),
    ]
