# Generated by Django 4.0.6 on 2022-10-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0018_documenttype_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('title',), 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типи документів'},
        ),
    ]
