# Generated by Django 4.0.6 on 2022-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0019_alter_documenttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='signer_type',
            field=models.CharField(blank=True, choices=[('collegium', 'Члени колегії та секретар справи'), ('collegium_head', 'Голова колегії')], max_length=16, null=True, verbose_name='Тип підписанта'),
        ),
    ]
