# Generated by Django 4.0.6 on 2022-11-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0020_documenttype_signer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('obj_kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifiers.objkind', verbose_name="Вид об'єкта промислової власності")),
            ],
            options={
                'verbose_name': 'Тип рішення АП',
                'verbose_name_plural': 'Типи рішень АП',
                'db_table': 'cl_decision_types',
            },
        ),
    ]
