# Generated by Django 4.0.6 on 2022-11-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0021_decisiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontype',
            name='obj_kind',
        ),
        migrations.AddField(
            model_name='decisiontype',
            name='claim_kinds',
            field=models.ManyToManyField(blank=True, to='classifiers.claimkind', verbose_name='Види звернень'),
        ),
    ]
