# Generated by Django 4.0.6 on 2022-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0024_commandtype_objkind_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimkind',
            name='abbr',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Абревіатура'),
        ),
    ]
