# Generated by Django 4.0.6 on 2022-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0026_alter_documenttype_signer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=512, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Тип особи звернення',
                'verbose_name_plural': 'Тип осіб звернення',
                'db_table': 'cl_claim_person_types',
            },
        ),
    ]
