# Generated by Django 4.0.6 on 2022-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0027_claimpersontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='signer_type',
            field=models.CharField(blank=True, choices=[('collegium', 'Члени колегії та секретар справи'), ('collegium_head', 'Голова колегії'), ('director', 'Директор організації')], max_length=16, null=True, verbose_name='Тип підписанта'),
        ),
    ]
