# Generated by Django 4.0.6 on 2022-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0028_alter_documenttype_signer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=512, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Причина припинення розгляду справи',
                'verbose_name_plural': 'Причини припинення розгляду справи',
                'db_table': 'cl_stop_reasons',
            },
        ),
    ]
