# Generated by Django 4.0.6 on 2022-10-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_document_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Час зарахування')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ким зараховано')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Справа')),
            ],
            options={
                'db_table': 'payments_payments_cases',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='case',
        ),
        migrations.AddField(
            model_name='payment',
            name='cases',
            field=models.ManyToManyField(blank=True, through='payments.PaymentCase', to='cases.case', verbose_name='Справи'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments_payments_list',
        ),
        migrations.AddField(
            model_name='paymentcase',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='Платіж'),
        ),
    ]
