# Generated by Django 4.0.6 on 2022-12-22 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.IntegerField(choices=[(1, 'Нове'), (2, 'У роботі'), (3, 'Виконано')], default=1, verbose_name='Статус')),
                ('text', models.TextField(verbose_name='Текст заявки')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/')),
                ('taken', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час прийняття у роботу')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час закриття заявки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_by', to=settings.AUTH_USER_MODEL, verbose_name='Закрив')),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
                ('taken_to_work_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_to_work_by', to=settings.AUTH_USER_MODEL, verbose_name='Прийняв у роботу')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
            },
        ),
    ]
