# Generated by Django 4.0.6 on 2022-12-28 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file_1',
            field=models.FileField(blank=True, help_text='Файл з зображенням (формати: jpg, gif, png)', null=True, upload_to='tickets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'gif', 'png'])], verbose_name='Файл 1'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file_2',
            field=models.FileField(blank=True, help_text='Файл з зображенням (формати: jpg, gif, png)', null=True, upload_to='tickets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'gif', 'png'])], verbose_name='Файл 2'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file_3',
            field=models.FileField(blank=True, help_text='Файл з зображенням (формати: jpg, gif, png)', null=True, upload_to='tickets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'gif', 'png'])], verbose_name='Файл 3'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(help_text='Будь ласка, детально опишіть проблему', max_length=2048, verbose_name='Текст заявки'),
        ),
    ]
