# Generated by Django 4.0.6 on 2022-10-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0036_remove_casestagestep_case_stopped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('datetime', models.DateTimeField(verbose_name='Дата та час засідання')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Справа')),
            ],
            options={
                'verbose_name': 'Засідання',
                'verbose_name_plural': 'Засідання',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('accepted', models.BooleanField(default=False, verbose_name='Запрошення прийнято')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час прийняття запрошення')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час відмовлення у запрошенні')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Засідання')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член колегії')),
            ],
            options={
                'verbose_name': 'Запрошення',
                'verbose_name_plural': 'Запрошення',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('date_from', models.DateField(verbose_name='Дата з')),
                ('date_to', models.DateField(verbose_name='Дата по')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член колегії')),
            ],
            options={
                'verbose_name': 'Відсутність співробітника АП',
                'verbose_name_plural': 'Відсутності співробітників АП',
            },
        ),
    ]
