# Generated by Django 4.0.6 on 2022-10-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='асідання підтверджено усіма учасниками'),
        ),
    ]
