# Generated by Django 4.0.6 on 2022-10-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='accepted',
        ),
    ]
