# Generated by Django 4.0.6 on 2022-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_invitation_accepted_remove_meeting_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('PRE', 'Попереднє засідання'), ('COMMON', 'Апеляційне засідання')], default='COMMON', max_length=6, verbose_name='Тип засідання'),
        ),
    ]
