# Generated by Django 4.0.6 on 2022-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('PRE', 'Підготовче засідання'), ('COMMON', 'Апеляційне засідання')], default='COMMON', max_length=6, verbose_name='Тип засідання'),
        ),
    ]
