# Generated by Django 4.0.6 on 2022-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.CharField(default='', max_length=255, verbose_name='Причина'),
        ),
    ]
