# Generated by Django 4.0.6 on 2022-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_absence_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Очікує'), ('DONE', 'Проведено')], default='PENDING', max_length=16, verbose_name='Статус засідання'),
        ),
    ]
