# Generated by Django 4.0.6 on 2022-12-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='video_meeting',
            field=models.BooleanField(default=False, verbose_name='Засідання у режимі відео-конференції'),
        ),
    ]
